# Site
name: "Hello non-IT people"
title: "Hello non-IT people"
description: "IT is often a black box for 'outsiders' with its own jargon, many abbreviations and often even its own culture. Things often sound very complex and new buzzwords pop up regularly with a new promise of speed, cost savings and future stability. Here you can find IT stuff explained and simplified."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
# google_analytics: 'G-TV4P1P6HH2'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Niels
    display_name: Niels
    avatar: 'assets/images/niels-avatar.png'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: info@nielstalens.nl
    web: https://nielstalens.nl
    linkedin: https://www.linkedin.com/in/nielstalens/
    description: "Author of Non-it people, freelance Product Owner and IT Lead. Recreational developer. Interested in building the right things right."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
